name: Build Henry IA

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v6

      - name: Configurar Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: "17"

      - name: Configurar Gradle
        uses: gradle/actions/setup-gradle@v6
        with:
          gradle-version: "9.5"

      - name: Compilar APK
        run: gradle assembleDebug

      - name: Disponibilizar APK
        uses: actions/upload-artifact@v4
        with:
          name: henry-ia-debug
          path: app/build/outputs/apk/debug/app-debug.apk
